name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - dev
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  upload-assets:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: build
        run: |
          sudo apt install -y zip unzip
          npm i -g yarn
          yarn install --frozen-lockfile
          yarn pdf
          yarn build

          bash zip.sh

      - uses: ncipollo/release-action@v1
        with:
          tag: nightly
          artifacts: "build/*.zip"
          allowUpdates: true

      - name: Upload ext-saladict-chrome
        uses: actions/upload-artifact@v4
        with:
          name: ext-saladict-chrome
          path: "build/ext-saladict-chrome.zip"
      - name: Upload ext-saladict-edge.zip
        uses: actions/upload-artifact@v4
        with:
          name: ext-saladict-edge
          path: "build/ext-saladict-edge.zip"
      - name: Upload ext-saladict-firefox
        uses: actions/upload-artifact@v4
        with:
          name: ext-saladict-firefox
          path: "build/ext-saladict-firefox.zip"
      - name: Upload ext-saladict-safari
        uses: actions/upload-artifact@v4
        with:
          name: ext-saladict-safari
          path: "build/ext-saladict-safari.zip"